@eCommerceServer__HostAddress = http://localhost:5208

POST http://localhost:5208/api/Auth/Login
Accept: application/json
Content-Type: application/json

{
  "email": "mehmetcanunaldi@gmail.com",
  "password": "String123"
}

###

GET https://localhost:7179/api/ShoppingCarts/GetAll
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI0IiwiRW1haWwiOiJtZWhtZXRjYW51bmFsZGlAZ21haWwuY29tIiwiTmFtZSI6Ik1laG1ldCBDYW4gw5xOQUxESSIsIm5iZiI6MTcwNDQ4NTIxMSwiZXhwIjoxNzA3MTYzNjExLCJpc3MiOiJNZWhtZXQgQ2FuIMOcTkFMREkiLCJhdWQiOiJsb2NhbGhvc3Q6NDIwMCJ9.AKzRYNimjkEU1wiD3bWxK9axd0qxp9SrsI_wcDcub92ZveHfDXD-5EjTRJVRLDrwjrssvZi_DS2PWfLNLXkexA

###
GET https://localhost:7179/api/Orders/GetAll
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI0IiwiRW1haWwiOiJtZWhtZXRjYW51bmFsZGlAZ21haWwuY29tIiwiTmFtZSI6Ik1laG1ldCBDYW4gw5xOQUxESSIsIm5iZiI6MTcwNDQ4NTIxMSwiZXhwIjoxNzA3MTYzNjExLCJpc3MiOiJNZWhtZXQgQ2FuIMOcTkFMREkiLCJhdWQiOiJsb2NhbGhvc3Q6NDIwMCJ9.AKzRYNimjkEU1wiD3bWxK9axd0qxp9SrsI_wcDcub92ZveHfDXD-5EjTRJVRLDrwjrssvZi_DS2PWfLNLXkexA

###